openapi: 3.0.0
info:
  title: Sample API
  version: '1.0'
servers:
  - url: http://localhost:5000
paths:
  /configloopback:
    post:
      description: Lets a user post loopback ip
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - ip
              properties:
                name:
                  type: string
                  pattern: '^[a-zA-Z0-9 ]*$'
                ip:
                  type: string
                  pattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'

      responses:
        '200':
          description: Successfully configured

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /deleteloopback:
    post:
      description: Lets a user delete loopback ip
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  pattern: '^[a-zA-Z0-9 ]*$'

      responses:
        '200':
          description: Successfully deleted

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

